<#
.SYNOPSIS
    Compiles the project's C# without opening Unity, and prints only what is wrong.

.DESCRIPTION
    Builds the .csproj files Unity generates, using the .NET SDK that ships inside the Unity
    install. Two things make this worth having:

      * It does not need the editor closed. This compiles the generated project against Unity's
        DLLs rather than driving the editor, so it runs happily while someone is mid-playtest.
        Unity's own -batchmode would block on the project lock.

      * It is fast once warm — a few seconds — which is quick enough to run before handing work
        over rather than after someone else has found the typo.

    It catches compile errors. It does not catch behaviour: a component whose Awake runs before
    its fields are assigned compiles perfectly, and so does a value silently overridden by a
    stale serialized asset. Both of those have cost this project real time. Treat a clean run as
    "worth someone's time to play", not as "works".

.PARAMETER Warnings
    Show warnings as well as errors. Off by default so a clean run is genuinely silent.

.EXAMPLE
    pwsh tools/compile-check.ps1
#>
[CmdletBinding()]
param([switch]$Warnings)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot

# Pin to the editor version the project actually declares, so an upgrade does not silently
# start checking against a different Unity than the one that will open it.
$versionFile = Join-Path $repo 'ProjectSettings/ProjectVersion.txt'
if (-not (Test-Path $versionFile)) { throw "Not a Unity project: no $versionFile" }

$version = (Select-String -Path $versionFile -Pattern '^m_EditorVersion:\s*(.+)$').Matches[0].Groups[1].Value.Trim()

$dotnet = "C:\Program Files\Unity\Hub\Editor\$version\Editor\Data\DotNetSdk\dotnet.exe"
if (-not (Test-Path $dotnet)) {
    throw "No .NET SDK inside Unity $version at $dotnet. Check the Hub install path."
}

# Generated by Unity and gitignored. If one is missing, Unity has not been asked to produce
# them — open the project once, or set an external editor in Preferences.
$projects = @('Assembly-CSharp.csproj', 'Assembly-CSharp-Editor.csproj') |
    Where-Object { Test-Path (Join-Path $repo $_) }

if (-not $projects) {
    throw "No generated .csproj found. Open the project in Unity once so it writes them."
}

# Everything MSBuild produces goes to temp. The repo keeps no build output, and nothing here
# can disturb the Library folder the editor is using.
$out = Join-Path ([System.IO.Path]::GetTempPath()) 'krz-compile-check'

$failed = $false
foreach ($proj in $projects) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($proj)
    Push-Location $repo
    try {
        $log = & $dotnet build $proj --nologo -v m `
            /p:OutputPath="$out\$name\bin\\" `
            /p:BaseIntermediateOutputPath="$out\$name\obj\\" 2>&1 | Out-String
    }
    finally { Pop-Location }

    $errors = $log -split "`r?`n" | Where-Object { $_ -match ': error ' } | Select-Object -Unique
    $warns  = $log -split "`r?`n" | Where-Object { $_ -match ': warning ' } | Select-Object -Unique

    if ($errors) {
        $failed = $true
        Write-Host "$name - $($errors.Count) error(s)" -ForegroundColor Red
        # Trimmed to the part a human reads: file, line, and what is wrong.
        $errors | ForEach-Object { Write-Host ("  " + ($_ -replace [regex]::Escape($repo + '\'), '' -replace ' \[.*\]$', '')) }
    }
    elseif ($Warnings -and $warns) {
        Write-Host "$name - clean, $($warns.Count) warning(s)" -ForegroundColor Yellow
        $warns | ForEach-Object { Write-Host ("  " + ($_ -replace [regex]::Escape($repo + '\'), '' -replace ' \[.*\]$', '')) }
    }
    else {
        Write-Host "$name - clean" -ForegroundColor Green
    }
}

if ($failed) { exit 1 }
